// swift-tools-version:5.6
//===----------------------------------------------------------------------===//
//
// This source file is part of the Soto for AWS open source project
//
// Copyright (c) 2017-2020 the Soto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Soto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import PackageDescription

let package = Package(
    name: "soto",
    platforms: [.iOS(.v12), .tvOS(.v12), .watchOS(.v5)],
    products: [
        .library(name: "SotoACM", targets: ["SotoACM"]),
        .library(name: "SotoACMPCA", targets: ["SotoACMPCA"]),
        .library(name: "SotoAPIGateway", targets: ["SotoAPIGateway"]),
        .library(name: "SotoAccessAnalyzer", targets: ["SotoAccessAnalyzer"]),
        .library(name: "SotoAccount", targets: ["SotoAccount"]),
        .library(name: "SotoAlexaForBusiness", targets: ["SotoAlexaForBusiness"]),
        .library(name: "SotoAmp", targets: ["SotoAmp"]),
        .library(name: "SotoAmplify", targets: ["SotoAmplify"]),
        .library(name: "SotoAmplifyBackend", targets: ["SotoAmplifyBackend"]),
        .library(name: "SotoAmplifyUIBuilder", targets: ["SotoAmplifyUIBuilder"]),
        .library(name: "SotoApiGatewayManagementApi", targets: ["SotoApiGatewayManagementApi"]),
        .library(name: "SotoApiGatewayV2", targets: ["SotoApiGatewayV2"]),
        .library(name: "SotoAppConfig", targets: ["SotoAppConfig"]),
        .library(name: "SotoAppConfigData", targets: ["SotoAppConfigData"]),
        .library(name: "SotoAppIntegrations", targets: ["SotoAppIntegrations"]),
        .library(name: "SotoAppMesh", targets: ["SotoAppMesh"]),
        .library(name: "SotoAppRunner", targets: ["SotoAppRunner"]),
        .library(name: "SotoAppStream", targets: ["SotoAppStream"]),
        .library(name: "SotoAppSync", targets: ["SotoAppSync"]),
        .library(name: "SotoAppflow", targets: ["SotoAppflow"]),
        .library(name: "SotoApplicationAutoScaling", targets: ["SotoApplicationAutoScaling"]),
        .library(name: "SotoApplicationCostProfiler", targets: ["SotoApplicationCostProfiler"]),
        .library(name: "SotoApplicationDiscoveryService", targets: ["SotoApplicationDiscoveryService"]),
        .library(name: "SotoApplicationInsights", targets: ["SotoApplicationInsights"]),
        .library(name: "SotoAthena", targets: ["SotoAthena"]),
        .library(name: "SotoAuditManager", targets: ["SotoAuditManager"]),
        .library(name: "SotoAutoScaling", targets: ["SotoAutoScaling"]),
        .library(name: "SotoAutoScalingPlans", targets: ["SotoAutoScalingPlans"]),
        .library(name: "SotoBackup", targets: ["SotoBackup"]),
        .library(name: "SotoBackupGateway", targets: ["SotoBackupGateway"]),
        .library(name: "SotoBackupStorage", targets: ["SotoBackupStorage"]),
        .library(name: "SotoBatch", targets: ["SotoBatch"]),
        .library(name: "SotoBillingconductor", targets: ["SotoBillingconductor"]),
        .library(name: "SotoBraket", targets: ["SotoBraket"]),
        .library(name: "SotoBudgets", targets: ["SotoBudgets"]),
        .library(name: "SotoChime", targets: ["SotoChime"]),
        .library(name: "SotoChimeSDKIdentity", targets: ["SotoChimeSDKIdentity"]),
        .library(name: "SotoChimeSDKMediaPipelines", targets: ["SotoChimeSDKMediaPipelines"]),
        .library(name: "SotoChimeSDKMeetings", targets: ["SotoChimeSDKMeetings"]),
        .library(name: "SotoChimeSDKMessaging", targets: ["SotoChimeSDKMessaging"]),
        .library(name: "SotoChimeSDKVoice", targets: ["SotoChimeSDKVoice"]),
        .library(name: "SotoCloud9", targets: ["SotoCloud9"]),
        .library(name: "SotoCloudControl", targets: ["SotoCloudControl"]),
        .library(name: "SotoCloudDirectory", targets: ["SotoCloudDirectory"]),
        .library(name: "SotoCloudFormation", targets: ["SotoCloudFormation"]),
        .library(name: "SotoCloudFront", targets: ["SotoCloudFront"]),
        .library(name: "SotoCloudHSM", targets: ["SotoCloudHSM"]),
        .library(name: "SotoCloudHSMV2", targets: ["SotoCloudHSMV2"]),
        .library(name: "SotoCloudSearch", targets: ["SotoCloudSearch"]),
        .library(name: "SotoCloudSearchDomain", targets: ["SotoCloudSearchDomain"]),
        .library(name: "SotoCloudTrail", targets: ["SotoCloudTrail"]),
        .library(name: "SotoCloudWatch", targets: ["SotoCloudWatch"]),
        .library(name: "SotoCloudWatchEvents", targets: ["SotoCloudWatchEvents"]),
        .library(name: "SotoCloudWatchLogs", targets: ["SotoCloudWatchLogs"]),
        .library(name: "SotoCodeArtifact", targets: ["SotoCodeArtifact"]),
        .library(name: "SotoCodeBuild", targets: ["SotoCodeBuild"]),
        .library(name: "SotoCodeCommit", targets: ["SotoCodeCommit"]),
        .library(name: "SotoCodeDeploy", targets: ["SotoCodeDeploy"]),
        .library(name: "SotoCodeGuruProfiler", targets: ["SotoCodeGuruProfiler"]),
        .library(name: "SotoCodeGuruReviewer", targets: ["SotoCodeGuruReviewer"]),
        .library(name: "SotoCodePipeline", targets: ["SotoCodePipeline"]),
        .library(name: "SotoCodeStar", targets: ["SotoCodeStar"]),
        .library(name: "SotoCodeStarConnections", targets: ["SotoCodeStarConnections"]),
        .library(name: "SotoCodeStarNotifications", targets: ["SotoCodeStarNotifications"]),
        .library(name: "SotoCognitoIdentity", targets: ["SotoCognitoIdentity"]),
        .library(name: "SotoCognitoIdentityProvider", targets: ["SotoCognitoIdentityProvider"]),
        .library(name: "SotoCognitoSync", targets: ["SotoCognitoSync"]),
        .library(name: "SotoComprehend", targets: ["SotoComprehend"]),
        .library(name: "SotoComprehendMedical", targets: ["SotoComprehendMedical"]),
        .library(name: "SotoComputeOptimizer", targets: ["SotoComputeOptimizer"]),
        .library(name: "SotoConfigService", targets: ["SotoConfigService"]),
        .library(name: "SotoConnect", targets: ["SotoConnect"]),
        .library(name: "SotoConnectCampaigns", targets: ["SotoConnectCampaigns"]),
        .library(name: "SotoConnectCases", targets: ["SotoConnectCases"]),
        .library(name: "SotoConnectContactLens", targets: ["SotoConnectContactLens"]),
        .library(name: "SotoConnectParticipant", targets: ["SotoConnectParticipant"]),
        .library(name: "SotoControlTower", targets: ["SotoControlTower"]),
        .library(name: "SotoCostAndUsageReportService", targets: ["SotoCostAndUsageReportService"]),
        .library(name: "SotoCostExplorer", targets: ["SotoCostExplorer"]),
        .library(name: "SotoCustomerProfiles", targets: ["SotoCustomerProfiles"]),
        .library(name: "SotoDAX", targets: ["SotoDAX"]),
        .library(name: "SotoDLM", targets: ["SotoDLM"]),
        .library(name: "SotoDataBrew", targets: ["SotoDataBrew"]),
        .library(name: "SotoDataExchange", targets: ["SotoDataExchange"]),
        .library(name: "SotoDataPipeline", targets: ["SotoDataPipeline"]),
        .library(name: "SotoDataSync", targets: ["SotoDataSync"]),
        .library(name: "SotoDatabaseMigrationService", targets: ["SotoDatabaseMigrationService"]),
        .library(name: "SotoDetective", targets: ["SotoDetective"]),
        .library(name: "SotoDevOpsGuru", targets: ["SotoDevOpsGuru"]),
        .library(name: "SotoDeviceFarm", targets: ["SotoDeviceFarm"]),
        .library(name: "SotoDirectConnect", targets: ["SotoDirectConnect"]),
        .library(name: "SotoDirectoryService", targets: ["SotoDirectoryService"]),
        .library(name: "SotoDocDB", targets: ["SotoDocDB"]),
        .library(name: "SotoDrs", targets: ["SotoDrs"]),
        .library(name: "SotoDynamoDB", targets: ["SotoDynamoDB"]),
        .library(name: "SotoDynamoDBStreams", targets: ["SotoDynamoDBStreams"]),
        .library(name: "SotoEBS", targets: ["SotoEBS"]),
        .library(name: "SotoEC2", targets: ["SotoEC2"]),
        .library(name: "SotoEC2InstanceConnect", targets: ["SotoEC2InstanceConnect"]),
        .library(name: "SotoECR", targets: ["SotoECR"]),
        .library(name: "SotoECRPublic", targets: ["SotoECRPublic"]),
        .library(name: "SotoECS", targets: ["SotoECS"]),
        .library(name: "SotoEFS", targets: ["SotoEFS"]),
        .library(name: "SotoEKS", targets: ["SotoEKS"]),
        .library(name: "SotoEMR", targets: ["SotoEMR"]),
        .library(name: "SotoEMRContainers", targets: ["SotoEMRContainers"]),
        .library(name: "SotoEMRServerless", targets: ["SotoEMRServerless"]),
        .library(name: "SotoElastiCache", targets: ["SotoElastiCache"]),
        .library(name: "SotoElasticBeanstalk", targets: ["SotoElasticBeanstalk"]),
        .library(name: "SotoElasticInference", targets: ["SotoElasticInference"]),
        .library(name: "SotoElasticLoadBalancing", targets: ["SotoElasticLoadBalancing"]),
        .library(name: "SotoElasticLoadBalancingV2", targets: ["SotoElasticLoadBalancingV2"]),
        .library(name: "SotoElasticTranscoder", targets: ["SotoElasticTranscoder"]),
        .library(name: "SotoElasticsearchService", targets: ["SotoElasticsearchService"]),
        .library(name: "SotoEventBridge", targets: ["SotoEventBridge"]),
        .library(name: "SotoEvidently", targets: ["SotoEvidently"]),
        .library(name: "SotoFIS", targets: ["SotoFIS"]),
        .library(name: "SotoFMS", targets: ["SotoFMS"]),
        .library(name: "SotoFSx", targets: ["SotoFSx"]),
        .library(name: "SotoFinspace", targets: ["SotoFinspace"]),
        .library(name: "SotoFinspaceData", targets: ["SotoFinspaceData"]),
        .library(name: "SotoFirehose", targets: ["SotoFirehose"]),
        .library(name: "SotoForecast", targets: ["SotoForecast"]),
        .library(name: "SotoForecastquery", targets: ["SotoForecastquery"]),
        .library(name: "SotoFraudDetector", targets: ["SotoFraudDetector"]),
        .library(name: "SotoGameLift", targets: ["SotoGameLift"]),
        .library(name: "SotoGameSparks", targets: ["SotoGameSparks"]),
        .library(name: "SotoGlacier", targets: ["SotoGlacier"]),
        .library(name: "SotoGlobalAccelerator", targets: ["SotoGlobalAccelerator"]),
        .library(name: "SotoGlue", targets: ["SotoGlue"]),
        .library(name: "SotoGrafana", targets: ["SotoGrafana"]),
        .library(name: "SotoGreengrass", targets: ["SotoGreengrass"]),
        .library(name: "SotoGreengrassV2", targets: ["SotoGreengrassV2"]),
        .library(name: "SotoGroundStation", targets: ["SotoGroundStation"]),
        .library(name: "SotoGuardDuty", targets: ["SotoGuardDuty"]),
        .library(name: "SotoHealth", targets: ["SotoHealth"]),
        .library(name: "SotoHealthLake", targets: ["SotoHealthLake"]),
        .library(name: "SotoHoneycode", targets: ["SotoHoneycode"]),
        .library(name: "SotoIAM", targets: ["SotoIAM"]),
        .library(name: "SotoIVS", targets: ["SotoIVS"]),
        .library(name: "SotoIdentityStore", targets: ["SotoIdentityStore"]),
        .library(name: "SotoImagebuilder", targets: ["SotoImagebuilder"]),
        .library(name: "SotoInspector", targets: ["SotoInspector"]),
        .library(name: "SotoInspector2", targets: ["SotoInspector2"]),
        .library(name: "SotoIoT", targets: ["SotoIoT"]),
        .library(name: "SotoIoT1ClickDevicesService", targets: ["SotoIoT1ClickDevicesService"]),
        .library(name: "SotoIoT1ClickProjects", targets: ["SotoIoT1ClickProjects"]),
        .library(name: "SotoIoTAnalytics", targets: ["SotoIoTAnalytics"]),
        .library(name: "SotoIoTDataPlane", targets: ["SotoIoTDataPlane"]),
        .library(name: "SotoIoTDeviceAdvisor", targets: ["SotoIoTDeviceAdvisor"]),
        .library(name: "SotoIoTEvents", targets: ["SotoIoTEvents"]),
        .library(name: "SotoIoTEventsData", targets: ["SotoIoTEventsData"]),
        .library(name: "SotoIoTFleetHub", targets: ["SotoIoTFleetHub"]),
        .library(name: "SotoIoTFleetWise", targets: ["SotoIoTFleetWise"]),
        .library(name: "SotoIoTJobsDataPlane", targets: ["SotoIoTJobsDataPlane"]),
        .library(name: "SotoIoTRoboRunner", targets: ["SotoIoTRoboRunner"]),
        .library(name: "SotoIoTSecureTunneling", targets: ["SotoIoTSecureTunneling"]),
        .library(name: "SotoIoTSiteWise", targets: ["SotoIoTSiteWise"]),
        .library(name: "SotoIoTThingsGraph", targets: ["SotoIoTThingsGraph"]),
        .library(name: "SotoIoTTwinMaker", targets: ["SotoIoTTwinMaker"]),
        .library(name: "SotoIoTWireless", targets: ["SotoIoTWireless"]),
        .library(name: "SotoIvschat", targets: ["SotoIvschat"]),
        .library(name: "SotoKMS", targets: ["SotoKMS"]),
        .library(name: "SotoKafka", targets: ["SotoKafka"]),
        .library(name: "SotoKafkaConnect", targets: ["SotoKafkaConnect"]),
        .library(name: "SotoKendra", targets: ["SotoKendra"]),
        .library(name: "SotoKeyspaces", targets: ["SotoKeyspaces"]),
        .library(name: "SotoKinesis", targets: ["SotoKinesis"]),
        .library(name: "SotoKinesisAnalytics", targets: ["SotoKinesisAnalytics"]),
        .library(name: "SotoKinesisAnalyticsV2", targets: ["SotoKinesisAnalyticsV2"]),
        .library(name: "SotoKinesisVideo", targets: ["SotoKinesisVideo"]),
        .library(name: "SotoKinesisVideoArchivedMedia", targets: ["SotoKinesisVideoArchivedMedia"]),
        .library(name: "SotoKinesisVideoMedia", targets: ["SotoKinesisVideoMedia"]),
        .library(name: "SotoKinesisVideoSignaling", targets: ["SotoKinesisVideoSignaling"]),
        .library(name: "SotoLakeFormation", targets: ["SotoLakeFormation"]),
        .library(name: "SotoLambda", targets: ["SotoLambda"]),
        .library(name: "SotoLexModelBuildingService", targets: ["SotoLexModelBuildingService"]),
        .library(name: "SotoLexModelsV2", targets: ["SotoLexModelsV2"]),
        .library(name: "SotoLexRuntimeService", targets: ["SotoLexRuntimeService"]),
        .library(name: "SotoLexRuntimeV2", targets: ["SotoLexRuntimeV2"]),
        .library(name: "SotoLicenseManager", targets: ["SotoLicenseManager"]),
        .library(name: "SotoLicenseManagerUserSubscriptions", targets: ["SotoLicenseManagerUserSubscriptions"]),
        .library(name: "SotoLightsail", targets: ["SotoLightsail"]),
        .library(name: "SotoLocation", targets: ["SotoLocation"]),
        .library(name: "SotoLookoutEquipment", targets: ["SotoLookoutEquipment"]),
        .library(name: "SotoLookoutMetrics", targets: ["SotoLookoutMetrics"]),
        .library(name: "SotoLookoutVision", targets: ["SotoLookoutVision"]),
        .library(name: "SotoM2", targets: ["SotoM2"]),
        .library(name: "SotoMQ", targets: ["SotoMQ"]),
        .library(name: "SotoMTurk", targets: ["SotoMTurk"]),
        .library(name: "SotoMWAA", targets: ["SotoMWAA"]),
        .library(name: "SotoMachineLearning", targets: ["SotoMachineLearning"]),
        .library(name: "SotoMacie", targets: ["SotoMacie"]),
        .library(name: "SotoMacie2", targets: ["SotoMacie2"]),
        .library(name: "SotoManagedBlockchain", targets: ["SotoManagedBlockchain"]),
        .library(name: "SotoMarketplaceCatalog", targets: ["SotoMarketplaceCatalog"]),
        .library(name: "SotoMarketplaceCommerceAnalytics", targets: ["SotoMarketplaceCommerceAnalytics"]),
        .library(name: "SotoMarketplaceEntitlementService", targets: ["SotoMarketplaceEntitlementService"]),
        .library(name: "SotoMarketplaceMetering", targets: ["SotoMarketplaceMetering"]),
        .library(name: "SotoMediaConnect", targets: ["SotoMediaConnect"]),
        .library(name: "SotoMediaConvert", targets: ["SotoMediaConvert"]),
        .library(name: "SotoMediaLive", targets: ["SotoMediaLive"]),
        .library(name: "SotoMediaPackage", targets: ["SotoMediaPackage"]),
        .library(name: "SotoMediaPackageVod", targets: ["SotoMediaPackageVod"]),
        .library(name: "SotoMediaStore", targets: ["SotoMediaStore"]),
        .library(name: "SotoMediaStoreData", targets: ["SotoMediaStoreData"]),
        .library(name: "SotoMediaTailor", targets: ["SotoMediaTailor"]),
        .library(name: "SotoMemoryDB", targets: ["SotoMemoryDB"]),
        .library(name: "SotoMgn", targets: ["SotoMgn"]),
        .library(name: "SotoMigrationHub", targets: ["SotoMigrationHub"]),
        .library(name: "SotoMigrationHubConfig", targets: ["SotoMigrationHubConfig"]),
        .library(name: "SotoMigrationHubOrchestrator", targets: ["SotoMigrationHubOrchestrator"]),
        .library(name: "SotoMigrationHubRefactorSpaces", targets: ["SotoMigrationHubRefactorSpaces"]),
        .library(name: "SotoMigrationHubStrategy", targets: ["SotoMigrationHubStrategy"]),
        .library(name: "SotoMobile", targets: ["SotoMobile"]),
        .library(name: "SotoNeptune", targets: ["SotoNeptune"]),
        .library(name: "SotoNetworkFirewall", targets: ["SotoNetworkFirewall"]),
        .library(name: "SotoNetworkManager", targets: ["SotoNetworkManager"]),
        .library(name: "SotoNimble", targets: ["SotoNimble"]),
        .library(name: "SotoOpenSearch", targets: ["SotoOpenSearch"]),
        .library(name: "SotoOpsWorks", targets: ["SotoOpsWorks"]),
        .library(name: "SotoOpsWorksCM", targets: ["SotoOpsWorksCM"]),
        .library(name: "SotoOrganizations", targets: ["SotoOrganizations"]),
        .library(name: "SotoOutposts", targets: ["SotoOutposts"]),
        .library(name: "SotoPI", targets: ["SotoPI"]),
        .library(name: "SotoPanorama", targets: ["SotoPanorama"]),
        .library(name: "SotoPersonalize", targets: ["SotoPersonalize"]),
        .library(name: "SotoPersonalizeEvents", targets: ["SotoPersonalizeEvents"]),
        .library(name: "SotoPersonalizeRuntime", targets: ["SotoPersonalizeRuntime"]),
        .library(name: "SotoPinpoint", targets: ["SotoPinpoint"]),
        .library(name: "SotoPinpointEmail", targets: ["SotoPinpointEmail"]),
        .library(name: "SotoPinpointSMSVoice", targets: ["SotoPinpointSMSVoice"]),
        .library(name: "SotoPinpointSMSVoiceV2", targets: ["SotoPinpointSMSVoiceV2"]),
        .library(name: "SotoPolly", targets: ["SotoPolly"]),
        .library(name: "SotoPricing", targets: ["SotoPricing"]),
        .library(name: "SotoPrivateNetworks", targets: ["SotoPrivateNetworks"]),
        .library(name: "SotoProton", targets: ["SotoProton"]),
        .library(name: "SotoQLDB", targets: ["SotoQLDB"]),
        .library(name: "SotoQLDBSession", targets: ["SotoQLDBSession"]),
        .library(name: "SotoQuickSight", targets: ["SotoQuickSight"]),
        .library(name: "SotoRAM", targets: ["SotoRAM"]),
        .library(name: "SotoRDS", targets: ["SotoRDS"]),
        .library(name: "SotoRDSData", targets: ["SotoRDSData"]),
        .library(name: "SotoRUM", targets: ["SotoRUM"]),
        .library(name: "SotoRbin", targets: ["SotoRbin"]),
        .library(name: "SotoRedshift", targets: ["SotoRedshift"]),
        .library(name: "SotoRedshiftData", targets: ["SotoRedshiftData"]),
        .library(name: "SotoRedshiftServerless", targets: ["SotoRedshiftServerless"]),
        .library(name: "SotoRekognition", targets: ["SotoRekognition"]),
        .library(name: "SotoResiliencehub", targets: ["SotoResiliencehub"]),
        .library(name: "SotoResourceExplorer2", targets: ["SotoResourceExplorer2"]),
        .library(name: "SotoResourceGroups", targets: ["SotoResourceGroups"]),
        .library(name: "SotoResourceGroupsTaggingAPI", targets: ["SotoResourceGroupsTaggingAPI"]),
        .library(name: "SotoRoboMaker", targets: ["SotoRoboMaker"]),
        .library(name: "SotoRolesAnywhere", targets: ["SotoRolesAnywhere"]),
        .library(name: "SotoRoute53", targets: ["SotoRoute53"]),
        .library(name: "SotoRoute53Domains", targets: ["SotoRoute53Domains"]),
        .library(name: "SotoRoute53RecoveryCluster", targets: ["SotoRoute53RecoveryCluster"]),
        .library(name: "SotoRoute53RecoveryControlConfig", targets: ["SotoRoute53RecoveryControlConfig"]),
        .library(name: "SotoRoute53RecoveryReadiness", targets: ["SotoRoute53RecoveryReadiness"]),
        .library(name: "SotoRoute53Resolver", targets: ["SotoRoute53Resolver"]),
        .library(name: "SotoS3", targets: ["SotoS3"]),
        .library(name: "SotoS3Control", targets: ["SotoS3Control"]),
        .library(name: "SotoS3Outposts", targets: ["SotoS3Outposts"]),
        .library(name: "SotoSES", targets: ["SotoSES"]),
        .library(name: "SotoSESv2", targets: ["SotoSESv2"]),
        .library(name: "SotoSFN", targets: ["SotoSFN"]),
        .library(name: "SotoSMS", targets: ["SotoSMS"]),
        .library(name: "SotoSNS", targets: ["SotoSNS"]),
        .library(name: "SotoSQS", targets: ["SotoSQS"]),
        .library(name: "SotoSSM", targets: ["SotoSSM"]),
        .library(name: "SotoSSMContacts", targets: ["SotoSSMContacts"]),
        .library(name: "SotoSSMIncidents", targets: ["SotoSSMIncidents"]),
        .library(name: "SotoSSO", targets: ["SotoSSO"]),
        .library(name: "SotoSSOAdmin", targets: ["SotoSSOAdmin"]),
        .library(name: "SotoSSOOIDC", targets: ["SotoSSOOIDC"]),
        .library(name: "SotoSTS", targets: ["SotoSTS"]),
        .library(name: "SotoSWF", targets: ["SotoSWF"]),
        .library(name: "SotoSageMaker", targets: ["SotoSageMaker"]),
        .library(name: "SotoSageMakerA2IRuntime", targets: ["SotoSageMakerA2IRuntime"]),
        .library(name: "SotoSageMakerFeatureStoreRuntime", targets: ["SotoSageMakerFeatureStoreRuntime"]),
        .library(name: "SotoSageMakerRuntime", targets: ["SotoSageMakerRuntime"]),
        .library(name: "SotoSagemakerEdge", targets: ["SotoSagemakerEdge"]),
        .library(name: "SotoSavingsPlans", targets: ["SotoSavingsPlans"]),
        .library(name: "SotoScheduler", targets: ["SotoScheduler"]),
        .library(name: "SotoSchemas", targets: ["SotoSchemas"]),
        .library(name: "SotoSecretsManager", targets: ["SotoSecretsManager"]),
        .library(name: "SotoSecurityHub", targets: ["SotoSecurityHub"]),
        .library(name: "SotoServerlessApplicationRepository", targets: ["SotoServerlessApplicationRepository"]),
        .library(name: "SotoServiceCatalog", targets: ["SotoServiceCatalog"]),
        .library(name: "SotoServiceCatalogAppRegistry", targets: ["SotoServiceCatalogAppRegistry"]),
        .library(name: "SotoServiceDiscovery", targets: ["SotoServiceDiscovery"]),
        .library(name: "SotoServiceQuotas", targets: ["SotoServiceQuotas"]),
        .library(name: "SotoShield", targets: ["SotoShield"]),
        .library(name: "SotoSigner", targets: ["SotoSigner"]),
        .library(name: "SotoSnowDeviceManagement", targets: ["SotoSnowDeviceManagement"]),
        .library(name: "SotoSnowball", targets: ["SotoSnowball"]),
        .library(name: "SotoSsmSap", targets: ["SotoSsmSap"]),
        .library(name: "SotoStorageGateway", targets: ["SotoStorageGateway"]),
        .library(name: "SotoSupport", targets: ["SotoSupport"]),
        .library(name: "SotoSupportApp", targets: ["SotoSupportApp"]),
        .library(name: "SotoSynthetics", targets: ["SotoSynthetics"]),
        .library(name: "SotoTextract", targets: ["SotoTextract"]),
        .library(name: "SotoTimestreamQuery", targets: ["SotoTimestreamQuery"]),
        .library(name: "SotoTimestreamWrite", targets: ["SotoTimestreamWrite"]),
        .library(name: "SotoTranscribe", targets: ["SotoTranscribe"]),
        .library(name: "SotoTranscribeStreaming", targets: ["SotoTranscribeStreaming"]),
        .library(name: "SotoTransfer", targets: ["SotoTransfer"]),
        .library(name: "SotoTranslate", targets: ["SotoTranslate"]),
        .library(name: "SotoVoiceID", targets: ["SotoVoiceID"]),
        .library(name: "SotoWAF", targets: ["SotoWAF"]),
        .library(name: "SotoWAFRegional", targets: ["SotoWAFRegional"]),
        .library(name: "SotoWAFV2", targets: ["SotoWAFV2"]),
        .library(name: "SotoWellArchitected", targets: ["SotoWellArchitected"]),
        .library(name: "SotoWisdom", targets: ["SotoWisdom"]),
        .library(name: "SotoWorkDocs", targets: ["SotoWorkDocs"]),
        .library(name: "SotoWorkLink", targets: ["SotoWorkLink"]),
        .library(name: "SotoWorkMail", targets: ["SotoWorkMail"]),
        .library(name: "SotoWorkMailMessageFlow", targets: ["SotoWorkMailMessageFlow"]),
        .library(name: "SotoWorkSpaces", targets: ["SotoWorkSpaces"]),
        .library(name: "SotoWorkSpacesWeb", targets: ["SotoWorkSpacesWeb"]),
        .library(name: "SotoXRay", targets: ["SotoXRay"])
    ],
    dependencies: [
        .package(url: "https://github.com/soto-project/soto-core.git", branch: "main"),
        .package(url: "https://github.com/soto-project/soto-codegenerator", branch: "feature/plugin"),
    ],
    targets: [
        .target(name: "SotoACM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoACMPCA", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAPIGateway", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAccessAnalyzer", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAccount", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAlexaForBusiness", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAmp", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAmplify", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAmplifyBackend", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAmplifyUIBuilder", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoApiGatewayManagementApi", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoApiGatewayV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppConfig", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppConfigData", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppIntegrations", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppMesh", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppRunner", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppStream", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppSync", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAppflow", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoApplicationAutoScaling", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoApplicationCostProfiler", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoApplicationDiscoveryService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoApplicationInsights", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAthena", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAuditManager", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAutoScaling", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoAutoScalingPlans", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBackup", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBackupGateway", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBackupStorage", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBatch", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBillingconductor", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBraket", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoBudgets", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoChime", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoChimeSDKIdentity", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoChimeSDKMediaPipelines", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoChimeSDKMeetings", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoChimeSDKMessaging", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoChimeSDKVoice", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloud9", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudControl", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudDirectory", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudFormation", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudFront", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudHSM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudHSMV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudSearch", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudSearchDomain", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudTrail", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudWatch", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudWatchEvents", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCloudWatchLogs", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeArtifact", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeBuild", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeCommit", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeDeploy", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeGuruProfiler", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeGuruReviewer", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodePipeline", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeStar", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeStarConnections", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCodeStarNotifications", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCognitoIdentity", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCognitoIdentityProvider", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCognitoSync", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoComprehend", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoComprehendMedical", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoComputeOptimizer", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoConfigService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoConnect", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoConnectCampaigns", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoConnectCases", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoConnectContactLens", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoConnectParticipant", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoControlTower", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCostAndUsageReportService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCostExplorer", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoCustomerProfiles", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDAX", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDLM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDataBrew", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDataExchange", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDataPipeline", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDataSync", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDatabaseMigrationService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDetective", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDevOpsGuru", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDeviceFarm", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDirectConnect", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDirectoryService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDocDB", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDrs", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDynamoDB", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoDynamoDBStreams", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEBS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEC2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEC2InstanceConnect", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoECR", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoECRPublic", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoECS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEFS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEKS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEMR", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEMRContainers", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEMRServerless", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElastiCache", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElasticBeanstalk", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElasticInference", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElasticLoadBalancing", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElasticLoadBalancingV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElasticTranscoder", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoElasticsearchService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEventBridge", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoEvidently", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFIS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFMS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFSx", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFinspace", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFinspaceData", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFirehose", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoForecast", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoForecastquery", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoFraudDetector", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGameLift", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGameSparks", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGlacier", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGlobalAccelerator", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGlue", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGrafana", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGreengrass", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGreengrassV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGroundStation", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoGuardDuty", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoHealth", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoHealthLake", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoHoneycode", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIAM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIVS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIdentityStore", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoImagebuilder", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoInspector", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoInspector2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoT", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoT1ClickDevicesService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoT1ClickProjects", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTAnalytics", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTDataPlane", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTDeviceAdvisor", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTEvents", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTEventsData", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTFleetHub", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTFleetWise", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTJobsDataPlane", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTRoboRunner", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTSecureTunneling", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTSiteWise", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTThingsGraph", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTTwinMaker", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIoTWireless", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoIvschat", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKMS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKafka", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKafkaConnect", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKendra", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKeyspaces", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesis", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesisAnalytics", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesisAnalyticsV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesisVideo", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesisVideoArchivedMedia", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesisVideoMedia", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoKinesisVideoSignaling", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLakeFormation", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLambda", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLexModelBuildingService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLexModelsV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLexRuntimeService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLexRuntimeV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLicenseManager", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLicenseManagerUserSubscriptions", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLightsail", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLocation", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLookoutEquipment", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLookoutMetrics", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoLookoutVision", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoM2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMQ", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMTurk", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMWAA", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMachineLearning", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMacie", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMacie2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoManagedBlockchain", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMarketplaceCatalog", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMarketplaceCommerceAnalytics", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMarketplaceEntitlementService", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMarketplaceMetering", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaConnect", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaConvert", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaLive", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaPackage", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaPackageVod", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaStore", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaStoreData", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMediaTailor", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMemoryDB", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMgn", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMigrationHub", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMigrationHubConfig", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMigrationHubOrchestrator", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMigrationHubRefactorSpaces", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMigrationHubStrategy", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoMobile", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoNeptune", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoNetworkFirewall", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoNetworkManager", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoNimble", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoOpenSearch", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoOpsWorks", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoOpsWorksCM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoOrganizations", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoOutposts", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPI", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPanorama", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPersonalize", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPersonalizeEvents", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPersonalizeRuntime", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPinpoint", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPinpointEmail", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPinpointSMSVoice", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPinpointSMSVoiceV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPolly", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPricing", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoPrivateNetworks", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoProton", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoQLDB", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoQLDBSession", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoQuickSight", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRAM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRDS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRDSData", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRUM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRbin", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRedshift", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRedshiftData", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRedshiftServerless", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRekognition", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoResiliencehub", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoResourceExplorer2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoResourceGroups", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoResourceGroupsTaggingAPI", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoboMaker", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRolesAnywhere", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoute53", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoute53Domains", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoute53RecoveryCluster", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoute53RecoveryControlConfig", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoute53RecoveryReadiness", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoRoute53Resolver", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoS3", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoS3Control", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoS3Outposts", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSES", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSESv2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSFN", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSMS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSNS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSQS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSSM", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSSMContacts", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSSMIncidents", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSSO", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSSOAdmin", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSSOOIDC", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSTS", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSWF", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSageMaker", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSageMakerA2IRuntime", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSageMakerFeatureStoreRuntime", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSageMakerRuntime", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSagemakerEdge", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSavingsPlans", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoScheduler", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSchemas", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSecretsManager", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSecurityHub", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoServerlessApplicationRepository", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoServiceCatalog", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoServiceCatalogAppRegistry", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoServiceDiscovery", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoServiceQuotas", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoShield", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSigner", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSnowDeviceManagement", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSnowball", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSsmSap", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoStorageGateway", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSupport", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSupportApp", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoSynthetics", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTextract", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTimestreamQuery", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTimestreamWrite", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTranscribe", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTranscribeStreaming", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTransfer", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoTranslate", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoVoiceID", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWAF", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWAFRegional", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWAFV2", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWellArchitected", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWisdom", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWorkDocs", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWorkLink", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWorkMail", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWorkMailMessageFlow", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWorkSpaces", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoWorkSpacesWeb", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),
        .target(name: "SotoXRay", dependencies: [.product(name: "SotoCore", package: "soto-core")], plugins: [.plugin(name: "SotoCodeGeneratorPlugin", package: "soto-codegenerator")]),

        .testTarget(
            name: "SotoTests",
            dependencies: [
                "SotoACM",
                "SotoAPIGateway",
                "SotoApiGatewayV2",
                "SotoCloudFront",
                "SotoCloudTrail",
                "SotoDynamoDB",
                "SotoEC2",
                "SotoGlacier",
                "SotoIAM",
                "SotoLambda",
                "SotoRoute53",
                "SotoS3",
                "SotoS3Control",
                "SotoSES",
                "SotoSNS",
                "SotoSQS",
                "SotoSSM",
                "SotoSTS",
                "SotoTimestreamWrite"
            ]
        )
    ]
)
